"use client";

import StudyProgressBar from "./StudyProgressBar";

export default function FamilyIntro({
  onContinue,
  progressCurrent,
  progressTotal,
}: {
  onContinue: () => void;
  progressCurrent: number;
  progressTotal: number;
}) {
  return (
    <div>
      <StudyProgressBar
        current={progressCurrent}
        total={progressTotal}
        label="Family viewer"
      />
      <div className="max-w-lg mx-auto py-12 px-6">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-semibold text-gray-900 mb-2">
            Family Viewer Experience
          </h1>
          <p className="text-sm text-gray-400 leading-relaxed">
            You'll experience ClarityAI as a family member receiving updates
            about a loved one in the hospital.
          </p>
        </div>
        <div className="bg-white border border-gray-200 rounded-2xl p-6 flex flex-col gap-4 mb-6 text-sm text-gray-600 leading-relaxed">
          <p>
            <strong className="text-gray-800">What you'll see:</strong> A live
            update feed with three updates from a fictional patient's care
            team, generated by AI from clinical notes.
          </p>
          <p>
            <strong className="text-gray-800">What to do:</strong> Read
            through the updates as you would if a family member were
            hospitalized. You can expand the clinical details panel on each
            update.
          </p>
          <p>
            <strong className="text-gray-800">Patient:</strong> All
            information is completely fictional.
          </p>
        </div>
        <button
          onClick={onContinue}
          className="w-full bg-gray-900 text-white rounded-xl p-4 text-sm font-medium hover:bg-gray-700 transition-colors cursor-pointer"
        >
          View Family Updates
        </button>
      </div>
    </div>
  );
}