"use client";

import StudyProgressBar from "./StudyProgressBar";
import RatingScale from "./RatingScale";

export default function StudyDebrief({
  debriefReaction,
  setDebriefReaction,
  wouldWantThis,
  setWouldWantThis,
  easeOfUse,
  setEaseOfUse,
  compareToNow,
  setCompareToNow,
  openFeedback,
  setOpenFeedback,
  submitting,
  submitError,
  onSubmit,
  progressCurrent,
  progressTotal,
}: {
  debriefReaction: string;
  setDebriefReaction: (s: string) => void;
  wouldWantThis: string;
  setWouldWantThis: (s: string) => void;
  easeOfUse: number;
  setEaseOfUse: (n: number) => void;
  compareToNow: string;
  setCompareToNow: (s: string) => void;
  openFeedback: string;
  setOpenFeedback: (s: string) => void;
  submitting: boolean;
  submitError: string;
  onSubmit: () => void;
  progressCurrent: number;
  progressTotal: number;
}) {
  return (
    <div>
      <StudyProgressBar
        current={progressCurrent}
        total={progressTotal}
        label="Debrief"
      />
      <div className="max-w-lg mx-auto py-12 px-6">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-semibold text-gray-900 mb-2">
            Study Debrief
          </h1>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 mb-6 text-sm text-gray-700 leading-relaxed flex flex-col gap-3">
          <p className="font-semibold text-gray-900">
            The updates you read were generated by AI.
          </p>
          <p>
            ClarityAI is an AI system that transforms clinical patient data
            into plain-language family updates. Each scenario showed you one
            of three versions — raw clinical language, AI-simplified language,
            or AI-simplified with additional context.
          </p>
          <p>
            The purpose of this study is to understand which communication
            style best helps family members understand medical updates and
            manage anxiety. All scenarios were completely fictional.
          </p>
        </div>

        <div className="flex flex-col gap-5">
          <div className="bg-white border border-gray-200 rounded-2xl p-5">
            <p className="text-sm font-semibold text-gray-800 mb-3">
              Now that you know the messages were AI-generated, how do you
              feel about that? (optional)
            </p>
            <textarea
              value={debriefReaction}
              onChange={(e) => setDebriefReaction(e.target.value)}
              placeholder="Share your thoughts..."
              className="w-full bg-white border border-gray-200 rounded-xl p-3 text-sm text-gray-900 resize-none focus:outline-none focus:border-gray-400 transition-colors min-h-20"
            />
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5">
            <p className="text-sm font-semibold text-gray-800 mb-4">
              Would you want to receive updates this way if a family member
              was hospitalized?
            </p>
            <div className="flex flex-col gap-2">
              {[
                { value: "yes", label: "Yes" },
                { value: "maybe", label: "Maybe" },
                { value: "no", label: "No" },
              ].map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => setWouldWantThis(opt.value)}
                  className={`border rounded-xl p-3 text-sm text-left transition-all cursor-pointer ${
                    wouldWantThis === opt.value
                      ? "border-gray-900 bg-gray-900 text-white"
                      : "border-gray-200 text-gray-500 hover:border-gray-400"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5">
            <p className="text-sm font-semibold text-gray-800 mb-4">
              How easy was it to understand the updates you read?
            </p>
            <RatingScale
              value={easeOfUse}
              onChange={setEaseOfUse}
              lowLabel="Very hard"
              highLabel="Very easy"
            />
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5">
            <p className="text-sm font-semibold text-gray-800 mb-3">
              How does this compare to how you currently receive updates
              during hospitalizations? (optional)
            </p>
            <textarea
              value={compareToNow}
              onChange={(e) => setCompareToNow(e.target.value)}
              placeholder="Share your experience..."
              className="w-full bg-white border border-gray-200 rounded-xl p-3 text-sm text-gray-900 resize-none focus:outline-none focus:border-gray-400 transition-colors min-h-20"
            />
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5">
            <p className="text-sm font-semibold text-gray-800 mb-3">
              What would make this more useful to you? (optional)
            </p>
            <textarea
              value={openFeedback}
              onChange={(e) => setOpenFeedback(e.target.value)}
              placeholder="Any suggestions or feedback..."
              className="w-full bg-white border border-gray-200 rounded-xl p-3 text-sm text-gray-900 resize-none focus:outline-none focus:border-gray-400 transition-colors min-h-20"
            />
          </div>

          {submitError && (
            <p className="text-red-500 text-xs text-center">{submitError}</p>
          )}

          <button
            onClick={onSubmit}
            disabled={submitting}
            className="w-full bg-gray-900 text-white rounded-xl p-4 text-sm font-medium hover:bg-gray-700 transition-colors disabled:bg-gray-200 disabled:text-gray-400 disabled:cursor-not-allowed cursor-pointer"
          >
            {submitting ? "Submitting…" : "Submit & Finish"}
          </button>
        </div>
      </div>
    </div>
  );
}